### ISSUE TITLE
I can fly through turtle on stage 1

### ISSUE THREAD

**Issue by tt-77-temp** [GeFeC/Mario#5]
### **What's the issue**
There seems to be a collision bug in the game with the jumping enemy (a turtle), as the player is able to pass through the enemy while it is jumping. This can lead to frustrating gameplay experiences and disrupt the game's overall flow.

It appears that the collision detection is not properly detecting the enemy's hitbox during the jump animation. This may be due to a scripting issue or an error in the game's physics engine.

### **Suggestions**
I suggest looking into this issue and fixing it as soon as possible, as it can significantly impact the game's playability. It would be great to see this issue addressed in a future update.

Please let me know if there is any additional information needed to help resolve this bug. 

_Thank you for your attention to this matter._

**Comment by GeFeC** [comment]
Fixed
